### ISSUE TITLE
Incorrect image height for Dota Hero files

### ISSUE THREAD

**Issue by mdiller** [SteamDatabase/ValveResourceFormat#107]
When extracting the dota vpk files, some of the images have the incorrect dimensions, causing the rest of the pixels to be filled by clamping. The following files are in the dota_vpk in `dota 2 beta/game/dota/pak01_dir.vpk`.
The following are the image locations in the vpk:
`/panorama/images/heroes/npc_dota_hero_rubick_png.vtex_c`: (dimensions should be 128 x 72)
![npc_dota_hero_rubick_png](https://user-images.githubusercontent.com/3231343/44826455-f445fd00-abc3-11e8-8e1c-fafcf68849ee.png)
`/panorama/images/heroes/selection/npc_dota_hero_rubick_png.vtex_c`: (dimensions should be 71 x 94)
![npc_dota_hero_rubick_png](https://user-images.githubusercontent.com/3231343/44826463-032caf80-abc4-11e8-99d9-11cab5891bd5.png)
The images have dimensions of (128 x 128) instead of what they should be

**Comment by mdiller** [comment]
Another interesting note is that some of the files in the same directory are extracted with the correct dimensions.
`/panorama/images/heroes/selection/npc_dota_neutral_ghost_png.vtex`
![npc_dota_neutral_ghost_png](https://user-images.githubusercontent.com/3231343/44827038-1a6c9c80-abc6-11e8-992c-24672f5d5a04.png)

**Comment by SinZ163** [comment]
Unfortunately for us, we haven't been able to find where/if the correct dimensions are even stored in the file, and some of these problems show up in the asset browser

**Comment by AveYo** [comment]
Valve's own ` resourceinfo.exe -i test.vtex_c -game %dota% -debug tga -mip`  will have this issue.   
Ultimately a solution can be cooked up, since these _FillToPowerOfTwo_ textures can be identified, and padded bytes could be cut brute-force-ish.  
But the smart thing to do would be to use directx (or alternative?) functions to do the heavy lifting.  
D3DXCreateTextureFromFileEx / D3DXCreateTextureFromResourceEx  can return the actual image size in  D3DXIMAGE_INFO (must pass a pSrcInfo pointer when calling the function). 

working | bugged
---|---
 Block: REDI Size: `792 bytes [+0b padding]`| Block: REDI Size: `872 bytes [+0b padding]`
 Block: DATA Size: `1076 bytes [+26696b padding]`| Block: DATA Size: `1216 bytes [+16384b padding]`
_REDI Block (ResourceEditInfoBlock_t)_ |_REDI Block (ResourceEditInfoBlock_t)_ 
SpecialDependencies (3):|SpecialDependencies (4): 
`Texture Compiler Version`|`Texture Compiler Version` 
`Texture Compiler Version Mip None`|`Texture Compiler Version Mip None` 
`Texture Compiler Version Image Dilate Color`|`Texture Compiler Version Image YCoCg Conversion` 
`| __`Texture Compiler Version Image FillToPowerOfTwo`__ 
_vtex block DATA (1076 bytes)_ | _vtex block DATA (1216 bytes)_ 
Width = __71__| Width = __128__ 
Height = __94__| Height = __128__ 
Format = `4 (VTEX_FORMAT_RGBA8888)`| Format = `2 (VTEX_FORMAT_DXT5)` 
Extra Data = 1 entries:| Extra Data = 2 entries: 
VTEX_EXTRA_DATA_FALLBACK_BITS 1024 bytes|VTEX_EXTRA_DATA_FALLBACK_BITS 1024 bytes
`|{UNKNOWN DATA} (3) 128 bytes

**Comment by AveYo** [comment]
F🥇CK ME I'M A GENIUS!  
The `{UNKNOWN DATA} (3) 128 bytes` mentioned above actually has the source width and height!

    0x000440: 00 00 47 00 5e 00 00 00 00 00 00 00 00 00 00 00 | ..G.^...........
    0x000450: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
    0x000460: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
    0x000470: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
    0x000480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
    0x000490: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
    0x0004a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
    0x0004b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................

0x47 = 71 - source image width 👍 
0x5e = 94 - source image height 👍

**Comment by Marlamin** [comment]
![image](https://user-images.githubusercontent.com/50212/44843313-547e8280-ac48-11e8-9ba3-44bdf77f15f2.png)

**Comment by AveYo** [comment]
The Span stuff has broken this again!
