### ISSUE TITLE
DXT5nm Compression

### ISSUE THREAD

**Issue by DankParrot** [SteamDatabase/ValveResourceFormat#112]
Source 2 normal maps are compressed with [DXT5nm](http://wiki.polycount.com/wiki/Normal_Map_Compression#DXT5nm_Compression):

> DXT5nm is the same file format as DXT5 except before compression the red channel is moved into the alpha channel, the green channel is left as-is, and the red and blue channels are blanked with the same solid color.

When exporting a normal map, the output Red (x) channel should be the compiled texture's Alpha channel, the output Green (y) channel should stay the same and the output Blue (z) channel can be derived:
``` z = sqrt( 1 - x² - y² )```

This seems to apply to non-DXT5 normal maps too.

My guess is that the easiest way to check if a texture is a normal map would probably be to look for `NormalizeNormals` in the REDI special dependencies.

**Comment by xPaw** [comment]
How did you figure out that it's DXT5nm?

**Comment by DankParrot** [comment]
I tested it with a couple normal maps. My inputs were standard RGB normal maps and then the ones I extracted had no R or B channels, only G and A, and they matched up with their corresponding channels from the original map. I think I made a script at some point to try and reconstruct the third channel but it was really tedious.

If you look at a compiled normal map, they look Green and Pink instead of the usual purple-ish color of normal maps.

Example:
![copper_pot001_normal_psd_c6bb1779](https://user-images.githubusercontent.com/3376691/45600200-a09e2680-b9ad-11e8-837d-217bbc57d875.png)

**Comment by xPaw** [comment]
Want to make a PR?

**Comment by Perryvw** [comment]
Is it actually the responsibility of VRF to do this translation though, the preview image is the data that is actually present. Wouldn't it be up to the consuming party to transform that data however it sees fit?

**Comment by DankParrot** [comment]
> Is it actually the responsibility of VRF to do this translation though, the preview image is the data that is actually present. Wouldn't it be up to the consuming party to transform that data however it sees fit?

I could understand making it an optional setting, but the functionality should be there.
Generally people would want their extracted data in a more usable form, and DXT5nm is just considered another form of compression like DXT5 normally is.

> Want to make a PR?

@AveYo made a commit to fix this at AveYo@72956f2a9c0ad3769054ee9a7aebade5b5c9658a, however I could also implement it and PR in a few minutes.

**Comment by AveYo** [comment]
Just by looking at an example you can spot it is monochrome, but not gray-scale.  
Then you inspect the REDI and it should feature _"Texture Compiler Version Image NormalizeNormals"_  
There are no other identifiers except maybe the _Reflectivity_ values ( should only have Green and Alpha).  

Example: `grimstroke_fx_chain_normal_psd_eb08fc3e`
![fixed_grimstroke_fx_chain_normal_psd_eb08fc3e](https://i.imgur.com/JMzVRVZ.png)  ![grimstroke_fx_chain_normal_psd_eb08fc3e](https://i.imgur.com/IRgZyX1.png)  
Current output on the left, patch on the right  

If you treat it as YCoCg, and just replace alpha with 255 already gives a better output, but it's very bluish.  
It's the same with the formulas for CoCg_Y, so I went along with something else since it more closely resembles tangent space normalmaps.

**Comment by AveYo** [comment]
This thread going so fast..   
I wanted to point out that there is quite some difference in the samples I've provided!  
VRF is losing data, output only has one channel from the two present in the source!   
So you can't properly reconstruct the 3rd / or at least it is harder.  
My solution is not perfect either, but at least you can play around with inverting R G and H afterwards.

**Comment by DankParrot** [comment]
There's some details with how Source 2 handles normal maps that seem weird to me, I'm investigating that now. It seems the NM compression is applied even when there is no DXT5, and also sometimes the preview shows a different red channel to what I'd expect.

**Comment by AveYo** [comment]
You can't even preview such "normalizednormals" in the tools, I've just checked and it shows monochrome.  
100% Valve is using something else to generate the ones in games, and that's what you should do, too?

**Comment by DankParrot** [comment]
> You can't even preview such "normalizednormals" in the tools, I've just checked and it shows monochrome.
> 100% Valve is using something else to generate the ones in games, and that's what you should do, too?

As far as I can tell it's definitely DXT5nm compression. My weird issues are I believe some sort of ghost data and the way DXT5 works creating red/blue channels unintentionally that the engine doesn't use.

**Comment by AveYo** [comment]
There are some flags needed, hence to better create the normal maps outside the engine and just import them as dds? I'm not familiar with this stuff, it's [what I found quickly on google](http://www.ozone3d.net/tutorials/bump_map_compression_p3.php)

**Comment by DankParrot** [comment]
> There are some flags needed, hence to better create the normal maps outside the engine and just import them as dds? I'm not familiar with this stuff, it's [what I found quickly on google](http://www.ozone3d.net/tutorials/bump_map_compression_p3.php)

Oh, yeah, I mentioned that in my original post. I'll fork your fork and implement that and make a PR.

**Comment by AveYo** [comment]
I meant flags for creating your normal maps outside the engine. I can't see what you could do for the backward operation in VRF - my pr is solid but know yourself out 💃

**Comment by DankParrot** [comment]
> I meant flags for creating your normal maps outside the engine. I can't see what you could do for the backward operation in VRF - my pr is solid but know yourself out 💃

Your PR doesn't reconstruct the blue channel (the main background operation).
What you said was correct, it's calculated like: `z = sqrt( 1 - x² - y² )`

**Comment by AveYo** [comment]
Yep, but it's close enough, I'm not sure it warrants the code overhead (for sqrt).  
You can never perfectly reconstruct it, because you only have the green to work with _(as difference from alpha = red),_ and green has been passed lossly trough Rgb565. Unless I got it wrong?

**Comment by DankParrot** [comment]
> Yep, but it's close enough, I'm not sure it warrants the code overhead (for sqrt).
> You can never perfectly reconstruct it, because you only have the green to work with _(as difference from alpha = red),_ and green has been passed lossly trough Rgb565. Unless I got it wrong?

You're right but the sqrt is exactly how the engine decompresses it though, since you have the red _and_ the green channels you can calculate the blue channel with sqrt, which is why the engine discards the original blue channel, because it can always be calculated based on the other two.

**Comment by AveYo** [comment]
Just for fun I checked with sqrt-derived blue formula, and the result is not only close, but **identical**!   
As in - bit perfect 💃

**Comment by DankParrot** [comment]
> Just for fun I checked with sqrt-derived blue formula, and the result is not only close, but **identical**!
> As in - bit perfect 💃

Yep, it's like... the rules of math or something lol.

**Comment by AveYo** [comment]
Not sure you got it, but I meant identical to the one in current PR, without sqrt :)

**Comment by DankParrot** [comment]
> Not sure you got it, but I meant identical to the one in current PR, without sqrt :)

Oh, hrm, really, that makes me think Valve is using the R/B channels or something weird like that then, hrm...

**Comment by AveYo** [comment]
Yes they do stuff differently. They code their own tools. They make their own formats. You can never assume something works as in theory, or as documented, even if it's written by Valve. These guys (VRF) sure have bumped into such stuff every step of the way

**Comment by DankParrot** [comment]
**Left**: Original Image, **Right**: Decompiled output with your PR
<img alt="test_normal_rgb" src="https://user-images.githubusercontent.com/3376691/45601306-ee238f00-b9bf-11e8-9b78-818881c54514.png" width="256"> <img alt="test_normal_rgb_png_d4c9e195" src="https://user-images.githubusercontent.com/3376691/45601317-0f847b00-b9c0-11e8-90af-ee8abd595ae7.png" width="256">

Something's still missing here?

**Comment by AveYo** [comment]
At least all data is present, just channels being mixed.   
I've only worked with samples in dota, and I actually did not know how the source might have looked out, I simply forced it to look as a _tangent space normalmap_ and that might be why.  
Can you share your source in vtex_c compiled format? It would help sort this thing out

**Comment by DankParrot** [comment]
Okay, here's the original PNG, the compiled VTEX_C, and the extracted PNG.
[test_normal_maps.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/2387070/test_normal_maps.zip)

**Comment by DankParrot** [comment]
Here's how the engine reports it's compiling the normal map. It seems to be packing the gloss into R/B.
![steamtours_2018-09-16_15-34-52](https://user-images.githubusercontent.com/3376691/45601713-1c0bd200-b9c6-11e8-82b1-377c6b77bf5f.png)

**Comment by AveYo** [comment]
Yeah sry about that, late, no sleep, no coffee in sight until morning 👍

**Comment by DankParrot** [comment]
It looks to me like the normal map output is some sort of 2-channel diagonal magnitude generated from the usual XYZ normal map? I'm not sure though.

**Comment by DankParrot** [comment]
Might be something to do with the hemi-octahedron normal map encoding from Advanced VR Rendering (2015).

![image](https://user-images.githubusercontent.com/3376691/45602033-9f7bf200-b9cb-11e8-96ea-48385c5ac71b.png)

**Comment by AveYo** [comment]
That's only relevant to the initial phase = artistic source (not shared).  
Then it goes trough tangent-space color transformation (CoCgY) = source asset (in workshop tools).  
Then it goes trough DXT5 re-normalization / legacy source1 invert / other Valve stuff. We are here!

You can't even restore the CoCgY normal asset because DXT5 encode is lossy and we don't know (yet) the magic behind Valve's NormalizeNormals to recover _some_ of the original blue. Generic algorithms will produce worse results than simply force it at max value like I end up doing.  
I did experiment a bit with clipping the derived blue:
`z = sqrt( 1 - x² - y² )`  
`b = (1 - z > 1 / 3) ?  z : 1`  
Valve could be doing a bit more than the pseudo code above, and I don't see the point in pursuing it atm for a marginally increase in accuracy, as long as the current code produces a very close tangent space normal, reusable in any specific tool like ShaderMap 4

Here's your `test_normal_maps.zip` adjustments (I simply imported the source `test_normal_RGB.png` in WorkShop Tools Material Editor, with no extra stuff like the _HemiOctAnisoRoughness_ in your version)  
[aveyo_test_normal.zip](https://github.com/AveYo/ValveResourceFormat/files/2391805/aveyo_test_normal.zip)

**Comment by DankParrot** [comment]
I think we need to establish a few things here, DotA 2 Tools and SteamVR Home Tools encode normal maps differently. So we need to figure out both of those. My understanding is that SteamVR Home (and other VR stuff) uses the hemi-octohedron encoding and DotA 2 doesn't.

**Comment by Perryvw** [comment]
It is probably the client application deciding what to do with the texture data as I mentioned before. The texture can just be an image in the VPK without explicit use case. From a purely technical perspective I would not expect there is no reason why SteamVR can't use a texture as normal map and Dota using the same image as color map.

**Comment by DankParrot** [comment]
Yeah but the metadata is useful for attempting to get the source image back from a compiled texture.

**Comment by AveYo** [comment]
### In other news, I will update the PR shortly with perfect DXT5nm output!  
It helped going at it rested, and putting aside all assumptions about what Valve algorithms might do.  
Turns out it's really simple to derive the Blue component - I was just doing it wrong..  
_OP test source (using the cleaned up vtex_c in my zip)_  
![Imgur](https://i.imgur.com/YF2OPDp.png)  
_dota_addons/overthrow/materials/models/courier/lockjaw/lockjaw_normal_  
![Imgur](https://i.imgur.com/LGT4hSv.png)  
_dota_addons/overthrow/materials/models/props_structures/midas_throne/midas_kobold_props_normal
![Imgur](https://i.imgur.com/gzGiidt.png)  
Last one is also `LegacySource1InvertNormals`
