### ISSUE TITLE
Hemi-octohedron normal map projection in VR

### ISSUE THREAD

**Issue by DankParrot** [SteamDatabase/ValveResourceFormat#114]
SteamVR Home and other things using the VR Forward renderer compile normal maps by projecting them to use the bits in DXT5 more efficiently. They are decided by the shader (vr_standard).

See issue #112 for more and examples, which I will upload here later.

![45602033-9f7bf200-b9cb-11e8-96ea-48385c5ac71b](https://user-images.githubusercontent.com/3376691/45709162-31087280-bb38-11e8-955f-ddd1acc2c483.png)
(Image from Valve's "Advanced VR Rendering" at GDC 2015)

**Comment by AveYo** [comment]
Update: since OP did not provide the promised examples, here's some info:  
"Texture Compiler Version Mip HemiOctAnisoRoughness" packs 2 source images into one dxt5 texture,  one being the normal map, and the other being a roughness / anisotropic / gloss.

Obviously the dxt5nm patch is not suitable for these. I would say, it makes them worse (loss of detail).

Refactoring is needed to support either a layered output file (.psd?) or ability to export multiple png's from dxt5 decoder. A compromise is also possible to generate an "enhanced" normal map with more detail by combining the two sources.

Then the hard part comes since there is a lot of gpu-only magic done in shaders that is bloody impossible to imitate in cpu code.

But first, some examples with source would be great! @DankParrot

**Comment by DankParrot** [comment]
Here's an example from SteamVR:
![hemi-oct normal comparison](https://quak.ovh/e73b28.png)
Channels (left-to-right): R G B A
Top: RGB of normal map input
Bottom: Output normal

So it's like normal dxt5nm except the inputs are transformed to a hemi-oct.

**Comment by DankParrot** [comment]
Packing:
```
_color
RGB = color
A = refl

_normal
R . B = roughness
. G . A = normal

**Comment by DankParrot** [comment]
(whoops)

**Comment by AveYo** [comment]
That test image is not suitable as it has no native roughness, need an example not using default_gloss, but object source gloss, with R and G filled by it (not empty / 1px size).
I guess I could search in Steam VR vpk's myself when I manage to download it.

**Comment by DankParrot** [comment]
Here's an example using a custom gloss texture. Note that it's inverted from [the original](https://user-images.githubusercontent.com/3376691/49345108-1624a500-f635-11e8-8e9d-2d43532a686e.png) into a roughness map (so 1.0 is now pointing towards 0.0 black).


![image](https://user-images.githubusercontent.com/3376691/49345092-d493fa00-f634-11e8-8ae0-43c34ee8ab82.png)

And here's the original source files for the material, the normal and the gloss map:
 📎 [test_normal_01_src.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/2637412/test_normal_01_src.zip)

**Comment by lewa-j** [comment]
I think i made it. Using function from this http://jcgt.org/published/0003/02/01/
![vrf exe Screenshot 2020 03 28 - 17 14 59 77](https://user-images.githubusercontent.com/5416122/77825055-f19ce800-7117-11ea-93f6-5db63de8393b.png)
![vrf exe Screenshot 2020 03 28 - 17 15 06 26](https://user-images.githubusercontent.com/5416122/77825057-f366ab80-7117-11ea-908f-880476025163.png)
![vrf exe Screenshot 2020 03 28 - 17 15 09 02](https://user-images.githubusercontent.com/5416122/77825059-f5c90580-7117-11ea-9114-a08499480994.png)
![vrf exe Screenshot 2020 03 28 - 17 15 12 48](https://user-images.githubusercontent.com/5416122/77825061-f792c900-7117-11ea-9842-468dd48f47b7.png)

**Comment by AveYo** [comment]
I had some good results myself too at the time of this issue, without even finding that source,
but then had to resume fighting for my life so I dropped most stuff I did on a PC :(

**Comment by lewa-j** [comment]
TODO: figure out what "Texture Compiler Version Image Inverse" does

**Comment by lewa-j** [comment]
Good example materials/models/props_lab/server_09_normal_tga_3881d0a5.vtex_c
