### ISSUE TITLE
make this program for 32-bit os

### ISSUE THREAD

**Issue by ashaserv** [SteamDatabase/ValveResourceFormat#124]
I have win7 32 bit, and last your versions program only for 64 bit.

Please make build for 32 bit...

**Comment by xPaw** [comment]
32-bit support was dropped over 2 years ago and I see no reason to bring it back.

Upgrade your OS.

**Comment by ashaserv** [comment]
I have only 4 GB RAM and can not install 64 bit system + 95% of all programs what i use, for 32 bit system only.

Please make your program for 32 bit. Or your program need more than 4 GB RAM??

Latest version of framework 4.7.2 support win 32 bit and most self-respecting developers support both 32 bits and 64

**Comment by SinZ163** [comment]
Considering the main use case for VRF is Dota or VR games, and Valve doesn't support 32bit for dota's workshop tools which is what this library + tooling is trying to emulate

**Comment by yaakov-h** [comment]
Only 1.7% of Windows Steam users are running a 32-bit OS, though 10.2% of Steam users have 4GB of RAM. [[source]](https://store.steampowered.com/hwsurvey)

**Comment by Kiwi-1995** [comment]
Hi there OP. 

You don't need a 32 bit build because 64 bit operating systems have built in support for 32 bit. 99.9% of modern day operating systems are x86-64, therefore you can still run 32 bit libraries in addition to 64 bit libraries which also means you can run 32 bit applications under 64 bit operating systems.

The minimum requirement for most 64 bit operating systems is a x86-64 capable processor and at least 2GB of RAM with a recommendation of 4GB.

Additionally just because it is 64 bit only does not mean it will use more than 4GB. It is just an architecture limit.

As Yaakov just commented 94.37% of Steam clients that are ran on Windows are running a x86-64(64 bit) Windows operating system! 

Lastly Valve does not support 32 bit operating systems in Source 2. Which is understandable given that again 94.37% of Windows users are using a x86-64(64 bit) Windows operating system which again supports 32 bit applications and libraries.

It is understandable that 32 bit is not supported for various reasons.

If you can not install an x86-64/64 bit OS then I suggest upgrading your hardware so you can support this.

**Comment by ashaserv** [comment]
Valve support all games at this time on 32 bit and on 64 bit systems.

I don’t know why xpaw suddenly decided not to support a 32 bit system.
Maybe he just does not know how to make a build for a 32-bit system?

I just want extract dota 2 vpk's. And i would use the gcfcape, if she could understand the new vpks and open its.

Make please this program for 32 bit system. I'm not ask you (xpaw) support older systems ex. win xp or 98,95, but please support win 7 32/64 bit...

**Comment by xPaw** [comment]
You already got an answer, 32-bit support will not return.

To quote you "please support win 7 32/64 bit", I see no reason why Win7 64bit doesn't work?

**Comment by ashaserv** [comment]
I installed year ago win 7 32 bit on my old PC and already have lags if i launched steam client, game (ex. dota 2) and browser (firefox) at the same time. And you offer me install win 64 bit? In this case, I may be able to run 64-bit windows and nothing else. Those. can i run only one windows and no one program at the same time? Are you offering this to me?

I have old PC:

intel core 2 duo processor, 4 gb ram, nvidia 8800 gts 512 mb...

And i not think what you can not at physical reasons support 32 bit system. I think you are just too lazy to make build for 32 system(((

win 64 bit just requests big RAM and good processor and i'm not think what for your program need very many PC resources, so it requests only 64 bit system...

**Comment by xPaw** [comment]
It's time for you to upgrade your hardware.

**Comment by ashaserv** [comment]
Can you make final actucaL build for 32 bit? i downloaded GUI_0.09 and it can not open dota 2 vpk's
http://ashaserv.ru/img/xpaw_problem_1.PNG

**Comment by xPaw** [comment]
The answer is still no. No 32bit builds will be provided. Locking this issue because we are going in circles.
