### ISSUE TITLE
Ability to export several textures from one vtex_c

### ISSUE THREAD

**Issue by lewa-j** [SteamDatabase/ValveResourceFormat#212]
Some textures was created from several maps. 
For example:
lazlo002_jacket_normal_psd_6caddf9f is normal + roughness
lazlo002_body_color_psd_ed1b7ca5 is color + metalness.

**Comment by xPaw** [comment]
Is Valve's resourceinfo able to dump such textures into separate files, or does it act the same as we do?

And does the asset browser detect these separately as well?

**Comment by DankParrot** [comment]
Valve's resourceinfo (latest steamvr version) is currently actually broken and extracts textures incorrectly with all the mips kind of squished in there unless you do `-fullmip`.

And when you do use `-fullmip` one feature is that it actually ***does*** separate the alpha channels.

`models/props/quarantine/materials/combine_sign_cleanup_color_tga_ff0ed443.vtex_c`
![combine_sign_cleanup_color_tga_ff0ed443](https://user-images.githubusercontent.com/3376691/77838946-79d9b800-712d-11ea-8a78-5186d3aed254.jpg)

As for the asset browser, it doesn't consider compiled packed textures to be separate child assets (since they share the same vtex_c), but will display the input texture files as separate dependencies, and allows you to show all individual RGBA channels separately when viewing a vtex_c (like in #194).

![image](https://user-images.githubusercontent.com/3376691/77839211-a1ca1b00-712f-11ea-8e5b-cb5a2331df23.png)

**Comment by DankParrot** [comment]
You can figure out what textures are packed into a given vtex_c using REDI

**Comment by kristiker** [comment]
how the channels get mapped in shaders:
https://github.com/Facepunch/sbox-hover/blob/b36a20553be662ccafa9a361635e51cacdd8fa4c/shaders/damage.vfx#L75-L77
