### ISSUE TITLE
Audio controls

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#56]
We currently just play the sound as soon as it loads, not good.

**Comment by Marlamin** [comment]
Rude

**Comment by Marlamin** [comment]
Added a button to play the sound instead on click instead of right after opening. Seems NAudio is not sending the PlaybackCompleted event so the button will be stuck at pause indefinitely after the sound ends. Might need to look into whatever NAudio does and doing it ourselves instead. Should be doable for WAVs, not sure about MP3.

**Comment by xPaw** [comment]
We did get a better audio player in 3c22833357e1a5801893013aabc3f47ce1cb2805
