### ISSUE TITLE
Finish up export menu

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#59]
Add more types to it. Should it do anything in VPKs?

I guess we also can get rid of the right click on textures, no need to have it.

**Comment by SinZ163** [comment]
- [ ] Panorama
- [ ] SoundEventScript
- [ ] Texture
- [ ] Complete this list

**Comment by SinZ163** [comment]
Added an OBJ export option for Meshes in https://github.com/SteamDatabase/ValveResourceFormat/commit/a33b3a61341b4671f0ebfa35d894ed0b20e228a2 ![](http://i.imgur.com/SIlU30G.png)

**Comment by Perryvw** [comment]
Maybe we should export Collada DAE instead of FBX since collada is an open specification and C# FBX wrappers require the FBX SDK installed.

**Comment by MegaroboGuerrero** [comment]
Im a noob, Guys really thanks for your community JOB, please can youre explain to me how i can export the models, I dont have brain to put codes, Hope youre can explain to me.

**Comment by Ardarian** [comment]
So good that you support model exporting in some standart formats!
I hope that you'll release obj-exporting version soon, because I'm really looking forward to it, I quite need it, to be true, fbx would be better, but obj will be enough.

**Comment by Ardarian** [comment]
You know, about exporting obj... in my experience, when transfering mesh from one 3D program to another, it is better to have model in both OBJ and 3DS. Sometimes it really happens that one of them fails and is unoppenable by desired program, but never both.
(I speak about models from various games, not sure how or why, but even from one game one model crashes, but other 50 are fine)
Because of that I suggest to add 3DS exproting too.

**Comment by Ardarian** [comment]
When you export obj, you also need mtl file (UV cordinates)
It is nervewretching to retexture handy.
