### ISSUE TITLE
Add ctrl+w binding to close current tab

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#67]

**Comment by Wiethoofd** [comment]
Sorry for the bump, but from what I've experienced the current implementation (in 0.0.016.828) of this broke or has changed since.

Because currently pressing `ctrl+w` with multiple vpks loaded and files opened from these will **close all tabs except console**, instead of the current one.

I also found out that ctrl+e closes a tabs to the right, and ctrl+q the one to the left of the tab you are currently viewing, which is afaik not documented anywhere either.
